/* ================================================================ */
/* (C) 2005-2009 COPYRIGHT UNICOM SYSTEMS, INC.                     */
/*                                                                  */
/* ALL RIGHTS RESERVED                                              */
/*                                                                  */
/* THE INFORMATION CONTAINED HEREIN CONSTITUTES AN UNPUBLISHED      */
/* WORK OF UNICOM SYSTEMS, INC. ALL RIGHTS RESERVED.                */
/* NO MATERIAL FROM THIS WORK MAY BE REPRINTED,                     */
/* COPIED, OR EXTRACTED WITHOUT WRITTEN PERMISSION OF               */
/* UNICOM SYSTEMS, INC.                                             */
/* ================================================================ */

             CMD        PROMPT('Command #1')

             /* TST 1.101A */

             /* TST 1.111A - Add copyrights and new parameter */
             PARM       KWD(PARM1) TYPE(*CHAR) LEN(10) PROMPT('Parameter +
                          1')

